server:
    port: 8080

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always

springdoc:
    swagger-ui:
        url: openapi.json

stats-server-url: http://stats-server:9090
