server:
    port: 8080

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_HOST}:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
    swagger-ui:
        url: openapi.json

stats-server-url: http://${STATS_SERVER}:${STATS_PORT}

use-kafka: yes
