version: '3.1'
services:
  dozzle:
    image: amir20/dozzle
    ports:
      - "7070:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats-user
      - POSTGRES_PASSWORD=stats-password
    depends_on:
      - dozzle

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=ewm-password
    depends_on:
      - dozzle

  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - DB_USER=stats-user
      - DB_PASSWORD=stats-password
    depends_on:
      - dozzle
      - stats-db

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - DB_USER=ewm-user
      - DB_PASSWORD=ewm-password
      - STATS-SERVER=stats-server
      - STATS_PORT=9090
    depends_on:
      - dozzle
      - ewm-db
      - stats-server
