version: '3.1'
services:
  dozzle:
    image: amir20/dozzle
    ports:
      - "7070:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  stats-db:
    image: postgres:14-alpine
    ports:
      - "9091:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats-user
      - POSTGRES_PASSWORD=stats-password
    depends_on:
      - dozzle

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=ewm-password
    depends_on:
      - dozzle

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - dozzle

  kafka:
    image: bitnami/kafka:3.3.2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - dozzle
      - zookeeper

  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - DB_USER=stats-user
      - DB_PASSWORD=stats-password
      - KAFKA_HOST=kafka
    depends_on:
      - dozzle
      - stats-db
      - kafka

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - DB_USER=ewm-user
      - DB_PASSWORD=ewm-password
      - STATS_SERVER=stats-server
      - STATS_PORT=9090
      - KAFKA_HOST=kafka
    depends_on:
      - dozzle
      - ewm-db
      - kafka
      - stats-server
