version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats-user
      - POSTGRES_PASSWORD=stats-password

  ewm-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm-user
      - POSTGRES_PASSWORD=ewm-password

  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stats
      - DB_NAME_USER=stats-user
      - DB_PASSWORD=stats-password
    depends_on:
      - stats-db

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - DB_NAME_USER=ewm-user
      - DB_PASSWORD=ewm-password
    depends_on:
      - ewm-db
      - stats-server

