server:
    port: 9090

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: true
    sql:
        init:
            mode: always
    kafka:
        consumer:
            bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
            group-id: ewm_id
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
